site_name: Voxxed Days Bucharest
site_url: https://alina-yur.github.io/voxxed-bucharest
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
  favicon: assets/images/favicon.png
  font:
    text: Open Sans 
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-D5MSF4CYKX
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: https://github.com/alina-yur/voxxed-bucharest
repo_name: alina-yur/voxxed-bucharest